### PR TITLE
Multiple macOS fixes and improvements

### LINKED ISSUE #18: Required SFML installation on Mac
I recently downloaded the latest build on Mac OS X and it failed to run with the error
"tried: '/usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib' (no such file)"

Installing SFML using [homebrew](https://brew.sh/) with "brew install sfml" resolved the issue.

Noting for documentation purposes.

Thx!

### PR DESCRIPTION
**Pull request by orazioedoardo**
First off, thanks for resurrecting this game from the Classic era. I wanted to compile it for modern macOS but wasn’t comfortable granting [input monitoring](https://github.com/silverweed/lifish/issues/9) access to a non sandboxed and unsigned app, so that’s the first thing I fixed.

Turns out your event code worked, however the preprocessing directive enabling it was wrong. Even then, pressing a key on the keyboard triggered an input monitoring request, which is actually a SFML bug that I reported [here](https://github.com/SFML/SFML/issues/2843). As a stopgap waiting for a new release I patched out the offending function call.

Next, I noticed the binary crashed immediately on HiDPI configuration. This is an [SFML and/or Apple bug](https://github.com/SFML/SFML/issues/2300) that makes SFML return zero available full screen resolution, but this wasn’t accounted for, so I simply remove the full screen option from preferences in this case. Since on macOS an app can be maximized to fullscreen by pressing the green button in the menu bar anyway, not having the full screen option in preferences doesn’t seem a big deal.

Like basically apps on macOS, preferences and saves are now stored in `~/Library/ApplicationSupport/Boom Remake`, and assets are loaded from BOOM Remake.app/Contents/Resources.

I’ve also improved (basically replaced) the makeapp script with new version that downloads, patches and compiles SFML, as well as the app, with correctly linked frameworks (fixes https://github.com/silverweed/lifish/issues/18), Intel and Apple Silicon combined, and creates a DMG. A GitHub workflow is included to build the app on demand.

~~Only remaining Mac-specific issue as far as I can see is the fact that the app uses a lot of CPU by default even on the menu screen. The framerate is about 60 at the default 640p but decreases to 30 at 1080p. This doesn’t occur on Linux for example. Do you have any idea on what might be the issue or what to look for?~~

### CODE REVIEW

File: src/core/utils.hpp [hunk 1]
```diff
@@ -31,7 +31,7 @@ using Matrix = std::array<std::array<T, COLS>, ROWS>;
 /// Polyfill ///
 template<typename T>
 constexpr T abs(T num) {
-#ifdef IS_APPLE
+#ifdef __APPLE__
 	// Apple Clang is a "good" compiler...
 	if (num < 0) return -num;
```
Comment (silverweed) [inline src/core/utils.hpp]: I wonder if this workaround is still needed with newer versions of clang...maybe the ifdef can be removed entirely?

File: src/core/input/input_utils.hpp [hunk 2]
```diff
@@ -17,7 +17,7 @@ namespace kb {
 	/** If event is a KeyPressed/KeyReleased event, updates keyPressed status. */
 	void checkKeyPressed(sf::Event event);
 
-#	define IS_KEY_PRESSED lif::kb:isKeyPressed
+#	define IS_KEY_PRESSED lif::kb::isKeyPressed
```
Comment (silverweed) [inline src/core/input/input_utils.hpp:20]: Has this been broken until now? I admittedly haven't compiled the game on osx in years, so it wouldn't surprise me too much, but damn :|

File: src/lifish/preferences_persistence.hpp [hunk 3]
```diff
@@ -5,7 +5,12 @@
 
 namespace lif {
 
+#if defined(SFML_SYSTEM_MACOS)
+// Preferences file shouldn't be hidden
```
Comment (silverweed) [inline src/lifish/preferences_persistence.hpp]: Any reason why it shouldn't? 
Moreover, any reason why it shouldn't _specifically_ on mac?

File: src/core/Track.cpp [hunk 4]
```diff
@@ -4,7 +4,11 @@
 lif::Track lif::getNthTrack(int num, float start, float length) {
 	using lif::DIRSEP;
 	std::stringstream ss;
+#if defined(SFML_SYSTEM_MACOS)
```
Comment (silverweed) [inline src/core/Track.cpp]: I think you can remove the ifdef here and just use assetDir in all cases

File: src/core/core.cpp [hunk 5]
```diff
@@ -104,13 +102,19 @@ bool lif::initCore() {
 		return false;
 
 	// Fill the assetDir and saveDir variables once and for all
+#if defined(SFML_SYSTEM_MACOS)
+	// In addition to saved games, saveDir is also used to save preferences
+	assetDir = bundleResourcesPath() + DIRSEP;
+	saveDir = applicationSupportPath() + DIRSEP + "BOOM Remake" + DIRSEP;
```
Comment (silverweed) [inline src/core/core.cpp:110]: Do we _really_ want a space in the folder path, if we can help it?

File: src/ui/PreferencesScreen.cpp [hunk 6]
```diff
@@ -468,5 +475,9 @@ lif::ui::Action PreferencesScreen::_changeNPlayers(int newNPlayer) {
 
 void PreferencesScreen::onUnload() {
 	lif::ui::Screen::onUnload();
-	lif::savePreferences(lif::PREFERENCES_SAVE_FILE_NAME);
+	#if defined(SFML_SYSTEM_MACOS)
+		lif::savePreferences(std::string(lif::saveDir + std::string(lif::PREFERENCES_SAVE_FILE_NAME)).c_str());
```
Comment (silverweed) [inline src/ui/PreferencesScreen.cpp]: Since this is done in a couple of places maybe it's better to either have a `lif::getPreferencesPath()` function or building a `lif::preferencesPath` alongside `lif::assetDir` / `lif::saveDir`

**Comment by silverweed** [comment]
Thanks for the big contribution! I'm glad to see someone willing to support the poor neglected OSX version :D

Unfortunately I cannot test this myself right now, so all I can do is a not-too-in-depth code review. Looks good to me :-)
I just left a couple of comments before I merge this.

File: src/core/utils.hpp (hunk 1 above)
Comment (orazioedoardo) [reply src/core/utils.hpp]: I don't know, what should it affect on the game mechanics?

File: src/core/input/input_utils.hpp (hunk 2 above)
Comment (orazioedoardo) [reply src/core/input/input_utils.hpp:20]: This never compiled due to undefined `IS_APPLE` macro.

File: src/lifish/preferences_persistence.hpp (hunk 3 above)
Comment (orazioedoardo) [reply src/lifish/preferences_persistence.hpp]: Users might be surprised in case they open the `~/Library/ApplicationSupport/BOOM Remake` folder and see that it's "empty". Honestly, it shouldn't be hidden on other platforms too. On Linux it should be saved in `XDG_DATA_HOME/BOOM Remake/...` or `XDG_CONFIG_HOME/BOOM Remake/...` and `AppData` on Windows.

File: src/core/Track.cpp (hunk 4 above)
Comment (orazioedoardo) [reply src/core/Track.cpp]: Will do

File: src/core/core.cpp (hunk 5 above)
Comment (orazioedoardo) [reply src/core/core.cpp:110]: Other Mac apps with a space in the name also save in ApplicationSupport with the same space in the name.

File: src/ui/PreferencesScreen.cpp (hunk 6 above)
Comment (orazioedoardo) [reply src/ui/PreferencesScreen.cpp]: Will do

File: makeapp_osx.sh [hunk 7]
```diff
@@ -1,93 +1,44 @@
...
-	[[ -d "$LOCAL_FRAMEWORK_PATH/$i" ]] || {
-		echo "$i not found in $LOCAL_FRAMEWORK_PATH". >&2
-		exit 1
-	}
-done
+cmake -S . -B build -DRELEASE=true
+cmake --build build -j "$(sysctl -n hw.logicalcpu)"
 
-set -x
+sw_version="1.6"
```
Comment (orazioedoardo) [inline makeapp_osx.sh]: @silverweed Should this be 1.6.1? Note, you can create a release by running the workflow and downloading the artifact even if you don't have a Mac now.

File: src/core/utils.hpp (hunk 1 above)
Comment (silverweed) [reply src/core/utils.hpp]: IIRC the apple compiler didn't support constexpr std::abs when this was written, but I believe now it does, so the entire function could just return std::abs(num) on all platforms. Could you try removing the ifdef and see if it compiles?

File: src/core/core.cpp (hunk 5 above)
Comment (silverweed) [reply src/core/core.cpp:110]: I'll trust you on this since I'm not an expert in Mac conventions.

File: makeapp_osx.sh (hunk 7 above)
Comment (silverweed) [reply makeapp_osx.sh]: With all these changes I'd probably bump to 1.7. 
Not that I've been very consistent with versioning until now, but I believe it has enough visible changes to warrant a new minor.

**Comment by orazioedoardo** [comment]
I addressed the changes you suggested. Need to verify an issue with loading saved games but can't do it now. I will comment again when it's done. By the way, what about this if you don't mind?

> Only remaining Mac-specific issue as far as I can see is the fact that the app uses a lot of CPU by default even on the menu screen. The framerate is about 60 at the default 640p but decreases to 30 at 1080p. This doesn’t occur on Linux for example.

Seems to be prominent on high density display, not high resolution.

**Comment by stacksjb** [comment]
I tested this today and my brief testing of a build appears to be fully working and functional - thanks for the great work @orazioedoardo !

**Comment by orazioedoardo** [comment]
@stacksjb can you test this too?

> verify an issue with loading saved games

1. Download the build created by the script [here](https://github.com/orazioedoardo/lifish/actions/runs/7331864385/artifacts/1135444610) (or make your own)
2. Extract the .app to a folder (for example `~/Desktop`)
3. Save a game
4. Quit the app
5. Move the .app to another folder (for example `/Applications`)
6. Verify that the saved game can still be loaded.

Perhaps also check with TextEdit that the saved game at `~/Library/ApplicationSupport/BOOM Remake/name.lifish` has the `levelSet` key set to just `levels.json` and NOT a full path.

**Comment by stacksjb** [comment]
I tested save and load games, and while the saved game appears in the list after saving, attempting to load it returns 
"FATAL ERROR: Level set </Applications/Boom Remake.app/" does not exist or has bad format, so it looks like save/load is broken.

**Comment by orazioedoardo** [comment]
Thanks, can you send here the `.lifish` save file?

**Comment by stacksjb** [comment]
I had to rename so that github would allow upload - here you go [yay.lifish.txt](https://github.com/silverweed/lifish/files/13788433/yay.lifish.txt)

**Comment by orazioedoardo** [comment]
> it looks like save/load is broken

After moving the .app as I wrote or always?

**Comment by stacksjb** [comment]
Both; I tested with the app in my Apps folder and in my downloads.

**Comment by orazioedoardo** [comment]
If you save a game A when the app is in location X, close the app, then reopen and load A, does it work?

**Comment by stacksjb** [comment]
No - it does not.

**Comment by orazioedoardo** [comment]
What about [this](https://github.com/orazioedoardo/lifish/actions/runs/7351163314/artifacts/1138449785)? Try moving around the app, etc. send the save file regardless.

**Comment by stacksjb** [comment]
Tested game, two player, and load/save, including moving the binary to a different location, and it works as expected.

**Comment by stacksjb** [comment]
@silverweed  I'd love some documentation of the save game file format and paramaters if you're able to add comments into the code!

**Comment by stacksjb** [comment]
I am on an Intel MBP - I will test on M2 later today.

**Comment by orazioedoardo** [comment]
> Tested game, two player, and load/save, including moving around, and it works!

Cool, can you send the .lifish by the way? The levelSet key should contain only "levels.json" and not a full path.

**Comment by stacksjb** [comment]
[test.lifish.txt](https://github.com/silverweed/lifish/files/13789704/test.lifish.txt)

**Comment by cdstanford** [comment]
I tested on M1 and it's working great but I did encounter a crash when changing the fullscreen resolution several times

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               lifish [62663]
Path:                  /Volumes/VOLUME/*/BOOM Remake.app/Contents/MacOS/lifish
Identifier:            com.github.silverweed.lifish
Version:               1.7 (???)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-28 19:48:59.0667 -0700
OS Version:            macOS 12.3.1 (21E258)
Report Version:        12
Anonymous UUID:        9C1CB2E1-42F1-976E-1511-563AC9B50FD4

Sleep/Wake UUID:       47F69879-E8A2-4C44-815D-D50FB78A54A2

Time Awake Since Boot: 1200000 seconds
Time Since Wake:       294 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000011
Exception Codes:       0x0000000000000001, 0x0000000000000011
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [62663]

VM Region Info: 0x11 is not in any region.  Bytes before following region: 4333961199
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102530000-102604000    [  848K] r-x/r-x SM=COW  .../MacOS/lifish

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   sfml-graphics                 	       0x10292f7d8 sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) + 60
1   sfml-graphics                 	       0x10292f7ec sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) + 80
2   sfml-graphics                 	       0x10292f7ec sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) + 80
3   lifish                        	       0x1025d7ae8 lif::ui::Screen::draw(sf::RenderTarget&, sf::RenderStates) const + 108
4   sfml-graphics                 	       0x10292f7ec sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) + 80
5   sfml-graphics                 	       0x10292f7ec sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) + 80
6   lifish                        	       0x1025bfe9c main + 4088
7   dyld                          	       0x102aa1088 start + 516

Thread 1:
0   libsystem_pthread.dylib       	       0x1aa811078 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1aa811078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1aa811078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1aa811078 start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1aa7d88d0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1aa7d8d40 mach_msg + 76
2   CoreFoundation                	       0x1aa8e2c1c __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1aa8e10cc __CFRunLoopRun + 1180
4   CoreFoundation                	       0x1aa8e0490 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1ad5ac6f4 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x1aa81626c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1aa81108c thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	       0x1aa811078 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x1aa811078 start_wqthread + 0

Thread 8:: AMCP Logging Spool
0   libsystem_kernel.dylib        	       0x1aa7d890c semaphore_wait_trap + 8
1   caulk                         	       0x1b326aa2c caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x1b324e77c caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x1b324e39c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x1aa81626c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1aa81108c thread_start + 8

Thread 9:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	       0x1aa7d88d0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1aa7d8d40 mach_msg + 76
2   CoreAudio                     	       0x1ac522a40 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 104
3   CoreAudio                     	       0x1ac3afcd0 HALC_ProxyIOContext::IOWorkLoop() + 3396
4   CoreAudio                     	       0x1ac3ae990 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 100
5   CoreAudio                     	       0x1ac57ae60 HALB_IOThread::Entry(void*) + 88
6   libsystem_pthread.dylib       	       0x1aa81626c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1aa81108c thread_start + 8

Thread 10:
0   libsystem_kernel.dylib        	       0x1aa7d890c semaphore_wait_trap + 8
1   libdispatch.dylib             	       0x1aa65274c _dispatch_sema4_wait + 28
2   libdispatch.dylib             	       0x1aa652df4 _dispatch_semaphore_wait_slow + 132
3   OpenAL                        	       0x102d823ac alsem_wait + 20
4   OpenAL                        	       0x102d4f018 EventThread + 240
5   OpenAL                        	       0x102d82194 althrd_starter + 28
6   libsystem_pthread.dylib       	       0x1aa81626c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1aa81108c thread_start + 8

Thread 11:
0   libsystem_kernel.dylib        	       0x1aa7dc08c __semwait_signal + 8
1   libsystem_c.dylib             	       0x1aa6e4fbc nanosleep + 220
2   sfml-system                   	       0x1027dee04 sf::priv::sleepImpl(sf::Time) + 88
3   sfml-audio                    	       0x102873104 sf::SoundStream::streamData() + 776
4   sfml-system                   	       0x1027def30 sf::priv::ThreadImpl::entryPoint(void*) + 36
5   libsystem_pthread.dylib       	       0x1aa81626c _pthread_start + 148
6   libsystem_pthread.dylib       	       0x1aa81108c thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000016d8cf628   x1: 0x000000012510aa28   x2: 0x000000016d8cea50   x3: 0x0000600001d33510
    x4: 0x0000000000000020   x5: 0x0000000000000020   x6: 0x000060000135b000   x7: 0x0000000000000000
    x8: 0x000000016d8cf628   x9: 0x0000000000000001  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x00000000f684711c  x13: 0x0000000076847000  x14: 0x0000000076800000  x15: 0x0000000238cbcca8
   x16: 0x000000010292f79c  x17: 0x6ae1600001d334e0  x18: 0x0000000000000000  x19: 0x000000016d8ceb10
   x20: 0x000000016d8cf628  x21: 0x0000600001d70a20  x22: 0x0000600003d584f8  x23: 0x0000600003d584f8
   x24: 0xffffffffffffffff  x25: 0x0000000102612118  x26: 0x0000000000000001  x27: 0x0000000102612150
   x28: 0x0000000102610a88   fp: 0x000000016d8cea40   lr: 0x000000010292f7ec
    sp: 0x000000016d8ce9d0   pc: 0x000000010292f7d8 cpsr: 0x80001000
   far: 0x0000000000000011  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x1028e4000 -        0x10294ffff org.sfml-dev.sfml-graphics (2.6.1) <4163afc0-40f3-379e-a16a-5cc6c5066f78> /Volumes/VOLUME/*/BOOM Remake.app/Contents/Frameworks/sfml-graphics.framework/Versions/2.6.1/sfml-graphics
       0x102530000 -        0x102603fff com.github.silverweed.lifish (1.7) <c7f7c920-1843-3f22-92b8-93dd538f46e6> /Volumes/VOLUME/*/BOOM Remake.app/Contents/MacOS/lifish
       0x102a9c000 -        0x102afbfff dyld (*) <fbb89662-e6f2-3434-b542-f75185ac5e74> /usr/lib/dyld
       0x1aa80f000 -        0x1aa81bfff libsystem_pthread.dylib (*) <cee8bc77-6923-34d9-89a3-6f8f7279605e> /usr/lib/system/libsystem_pthread.dylib
       0x1aa7d7000 -        0x1aa80efff libsystem_kernel.dylib (*) <1d7b3b8e-75a1-34ea-aa52-9f7c23155c55> /usr/lib/system/libsystem_kernel.dylib
       0x1aa85e000 -        0x1aada3fff com.apple.CoreFoundation (6.9) <8e1809ff-f5b1-3d9e-be15-f2e7b1d8ce51> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1ad3fe000 -        0x1ae2b5fff com.apple.AppKit (6.9) <153590c1-624c-38fb-8ffb-ba751bccbd16> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1b324c000 -        0x1b3272fff com.apple.audio.caulk (1.0) <23d0d7ce-cb87-35f3-9c15-943bd8f6645a> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x1ac1ee000 -        0x1ac910fff com.apple.audio.CoreAudio (5.0) <51dd4b50-d2b2-31e7-acae-f662748a2d2b> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
       0x1aa64e000 -        0x1aa694fff libdispatch.dylib (*) <dc048e3b-e023-3d17-afe5-4ff3dc625608> /usr/lib/system/libdispatch.dylib
       0x102d3c000 -        0x102df7fff org.sfml-dev.OpenAL (*) <e78e2127-8590-3090-ab9b-1b467f7ed42a> /Volumes/VOLUME/*/BOOM Remake.app/Contents/Frameworks/OpenAL.framework/Versions/A/OpenAL
       0x1aa6d6000 -        0x1aa757fff libsystem_c.dylib (*) <fd566a15-42d8-314a-a99a-b59237ddf5bc> /usr/lib/system/libsystem_c.dylib
       0x1027d8000 -        0x1027dffff org.sfml-dev.sfml-system (2.6.1) <91685dbd-f75f-3f52-81fc-57d99cf6687e> /Volumes/VOLUME/*/BOOM Remake.app/Contents/Frameworks/sfml-system.framework/Versions/2.6.1/sfml-system
       0x102868000 -        0x102887fff org.sfml-dev.sfml-audio (2.6.1) <8eaffc6a-dbe8-3740-ae7c-cf26093e8e8a> /Volumes/VOLUME/*/BOOM Remake.app/Contents/Frameworks/sfml-audio.framework/Versions/2.6.1/sfml-audio
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=855.2M resident=0K(0%) swapped_out_or_unallocated=855.2M(100%)
Writable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               512K        4 
Activity Tracing                   256K        1 
CG backing stores                 1920K        4 
CG image                           160K        3 
ColorSync                          576K       25 
CoreAnimation                     15.7M        5 
CoreGraphics                        32K        2 
CoreUI image data                 1072K        7 
Foundation                          64K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           293.5M       55 
MALLOC guard page                  192K        9 
MALLOC_MEDIUM (reserved)         960.0M        8         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        128K        1 
STACK GUARD                       56.2M       12 
Stack                             15.3M       12 
VM_ALLOCATE                        640K       18 
VM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)
__AUTH                            1940K      190 
__AUTH_CONST                      11.3M      353 
__DATA                            9172K      353 
__DATA_CONST                      12.9M      367 
__DATA_DIRTY                       979K      123 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       585.7M       17 
__OBJC_CONST                      1988K      161 
__OBJC_RO                         82.9M        1 
__OBJC_RW                         3152K        1 
__TEXT                           269.5M      382 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      148.6M       21 
shared memory                      928K       16 
===========                     =======  ======= 
TOTAL                              2.8G     2160 
TOTAL, minus reserved VM space     1.5G     2160 



-----------
Full Report
-----------

{"app_name":"lifish","timestamp":"2023-12-28 19:49:01.00 -0700","app_version":"1.7","slice_uuid":"c7f7c920-1843-3f22-92b8-93dd538f46e6","build_version":"","platform":1,"bundleID":"com.github.silverweed.lifish","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3.1 (21E258)","incident_id":"58537B10-5F85-456A-92C7-C222D22C0700","name":"lifish"}
{
  "uptime" : 1200000,
  "procLaunch" : "2023-12-28 19:46:40.1323 -0700",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 31030143253503,
  "coalitionID" : 178706,
  "osVersion" : {
    "train" : "macOS 12.3.1",
    "build" : "21E258",
    "releaseType" : "User"
  },
  "captureTime" : "2023-12-28 19:48:59.0667 -0700",
  "incident" : "58537B10-5F85-456A-92C7-C222D22C0700",
  "bug_type" : "309",
  "pid" : 62663,
  "procExitAbsTime" : 31033475494792,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "lifish",
  "procPath" : "\/Volumes\/VOLUME\/*\/BOOM Remake.app\/Contents\/MacOS\/lifish",
  "bundleInfo" : {"CFBundleShortVersionString":"1.7","CFBundleIdentifier":"com.github.silverweed.lifish"},
  "storeInfo" : {"deviceIdentifierForVendor":"38BC4184-329E-5EE0-99CE-D0C3C1E7B5FE","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.github.silverweed.lifish",
  "crashReporterKey" : "9C1CB2E1-42F1-976E-1511-563AC9B50FD4",
  "wakeTime" : 294,
  "sleepWakeUUID" : "47F69879-E8A2-4C44-815D-D50FB78A54A2",
  "sip" : "enabled",
  "vmRegionInfo" : "0x11 is not in any region.  Bytes before following region: 4333961199\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      102530000-102604000    [  848K] r-x\/r-x SM=COW  ...\/MacOS\/lifish",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000011","rawCodes":[1,17],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000011"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":62663},
  "vmregioninfo" : "0x11 is not in any region.  Bytes before following region: 4333961199\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      102530000-102604000    [  848K] r-x\/r-x SM=COW  ...\/MacOS\/lifish",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":9651676,"threadState":{"x":[{"value":6132921896},{"value":4916816424},{"value":6132918864},{"value":105553146885392},{"value":32},{"value":32},{"value":105553136562176},{"value":0},{"value":6132921896},{"value":1},{"value":0},{"value":0},{"value":4135874844},{"value":1988390912},{"value":1988100096},{"value":9542814888},{"value":4338153372,"symbolLocation":0,"symbol":"sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&)"},{"value":7701542390927144160},{"value":0},{"value":6132919056},{"value":6132921896},{"value":105553147136544},{"value":105553180591352},{"value":105553180591352},{"value":18446744073709551615},{"value":4334887192,"symbolLocation":0,"symbol":"lif::options"},{"value":1},{"value":4334887248,"symbolLocation":0,"symbol":"lif::time"},{"value":4334881416,"symbolLocation":0,"symbol":"lif::ui::UI::getInstance()::instance"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4338153452},"cpsr":{"value":2147487744},"fp":{"value":6132918848},"sp":{"value":6132918736},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4338153432,"matchesCrashFrame":1},"far":{"value":17}},"queue":"com.apple.main-thread","frames":[{"imageOffset":309208,"symbol":"sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&)","symbolLocation":60,"imageIndex":0},{"imageOffset":309228,"symbol":"sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&)","symbolLocation":80,"imageIndex":0},{"imageOffset":309228,"symbol":"sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&)","symbolLocation":80,"imageIndex":0},{"imageOffset":686824,"symbol":"lif::ui::Screen::draw(sf::RenderTarget&, sf::RenderStates) const","symbolLocation":108,"imageIndex":1},{"imageOffset":309228,"symbol":"sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&)","symbolLocation":80,"imageIndex":0},{"imageOffset":309228,"symbol":"sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&)","symbolLocation":80,"imageIndex":0},{"imageOffset":589468,"symbol":"main","symbolLocation":4088,"imageIndex":1},{"imageOffset":20616,"symbol":"start","symbolLocation":516,"imageIndex":2}]},{"id":9651708,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":9651709,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":9651716,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":9651728,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":9651739,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6352,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":7488,"symbol":"mach_msg","symbolLocation":76,"imageIndex":4},{"imageOffset":543772,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":5},{"imageOffset":536780,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":5},{"imageOffset":533648,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":5},{"imageOffset":1763060,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":6},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":3},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":3}]},{"id":9651740,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":9651741,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":9651782,"name":"AMCP Logging Spool","frames":[{"imageOffset":6412,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":125484,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":7},{"imageOffset":10108,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":7},{"imageOffset":9116,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":7},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":3},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":3}]},{"id":9651799,"name":"com.apple.audio.IOThread.client","frames":[{"imageOffset":6352,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":7488,"symbol":"mach_msg","symbolLocation":76,"imageIndex":4},{"imageOffset":3361344,"symbol":"HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)","symbolLocation":104,"imageIndex":8},{"imageOffset":1842384,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":3396,"imageIndex":8},{"imageOffset":1837456,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":100,"imageIndex":8},{"imageOffset":3722848,"symbol":"HALB_IOThread::Entry(void*)","symbolLocation":88,"imageIndex":8},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":3},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":3}]},{"id":9651819,"frames":[{"imageOffset":6412,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":18252,"symbol":"_dispatch_sema4_wait","symbolLocation":28,"imageIndex":9},{"imageOffset":19956,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":132,"imageIndex":9},{"imageOffset":287660,"symbol":"alsem_wait","symbolLocation":20,"imageIndex":10},{"imageOffset":77848,"symbol":"EventThread","symbolLocation":240,"imageIndex":10},{"imageOffset":287124,"symbol":"althrd_starter","symbolLocation":28,"imageIndex":10},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":3},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":3}]},{"id":9651879,"frames":[{"imageOffset":20620,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":4},{"imageOffset":61372,"symbol":"nanosleep","symbolLocation":220,"imageIndex":11},{"imageOffset":28164,"symbol":"sf::priv::sleepImpl(sf::Time)","symbolLocation":88,"imageIndex":12},{"imageOffset":45316,"symbol":"sf::SoundStream::streamData()","symbolLocation":776,"imageIndex":13},{"imageOffset":28464,"symbol":"sf::priv::ThreadImpl::entryPoint(void*)","symbolLocation":36,"imageIndex":12},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":3},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":3}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4337844224,
    "CFBundleShortVersionString" : "2.6.1",
    "CFBundleIdentifier" : "org.sfml-dev.sfml-graphics",
    "size" : 442368,
    "uuid" : "4163afc0-40f3-379e-a16a-5cc6c5066f78",
    "path" : "\/Volumes\/VOLUME\/*\/BOOM Remake.app\/Contents\/Frameworks\/sfml-graphics.framework\/Versions\/2.6.1\/sfml-graphics",
    "name" : "sfml-graphics",
    "CFBundleVersion" : "2.6.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4333961216,
    "CFBundleShortVersionString" : "1.7",
    "CFBundleIdentifier" : "com.github.silverweed.lifish",
    "size" : 868352,
    "uuid" : "c7f7c920-1843-3f22-92b8-93dd538f46e6",
    "path" : "\/Volumes\/VOLUME\/*\/BOOM Remake.app\/Contents\/MacOS\/lifish",
    "name" : "lifish"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4339646464,
    "size" : 393216,
    "uuid" : "fbb89662-e6f2-3434-b542-f75185ac5e74",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7155544064,
    "size" : 53248,
    "uuid" : "cee8bc77-6923-34d9-89a3-6f8f7279605e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7155314688,
    "size" : 229376,
    "uuid" : "1d7b3b8e-75a1-34ea-aa52-9f7c23155c55",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7155867648,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5529600,
    "uuid" : "8e1809ff-f5b1-3d9e-be15-f2e7b1d8ce51",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1858.112"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7201611776,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15433728,
    "uuid" : "153590c1-624c-38fb-8ffb-ba751bccbd16",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.40.127"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7300497408,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 159744,
    "uuid" : "23d0d7ce-cb87-35f3-9c15-943bd8f6645a",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7182671872,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.audio.CoreAudio",
    "size" : 7483392,
    "uuid" : "51dd4b50-d2b2-31e7-acae-f662748a2d2b",
    "path" : "\/System\/Library\/Frameworks\/CoreAudio.framework\/Versions\/A\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "5.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7153704960,
    "size" : 290816,
    "uuid" : "dc048e3b-e023-3d17-afe5-4ff3dc625608",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4342398976,
    "CFBundleIdentifier" : "org.sfml-dev.OpenAL",
    "size" : 770048,
    "uuid" : "e78e2127-8590-3090-ab9b-1b467f7ed42a",
    "path" : "\/Volumes\/VOLUME\/*\/BOOM Remake.app\/Contents\/Frameworks\/OpenAL.framework\/Versions\/A\/OpenAL",
    "name" : "OpenAL",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7154262016,
    "size" : 532480,
    "uuid" : "fd566a15-42d8-314a-a99a-b59237ddf5bc",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4336746496,
    "CFBundleShortVersionString" : "2.6.1",
    "CFBundleIdentifier" : "org.sfml-dev.sfml-system",
    "size" : 32768,
    "uuid" : "91685dbd-f75f-3f52-81fc-57d99cf6687e",
    "path" : "\/Volumes\/VOLUME\/*\/BOOM Remake.app\/Contents\/Frameworks\/sfml-system.framework\/Versions\/2.6.1\/sfml-system",
    "name" : "sfml-system",
    "CFBundleVersion" : "2.6.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4337336320,
    "CFBundleShortVersionString" : "2.6.1",
    "CFBundleIdentifier" : "org.sfml-dev.sfml-audio",
    "size" : 131072,
    "uuid" : "8eaffc6a-dbe8-3740-ae7c-cf26093e8e8a",
    "path" : "\/Volumes\/VOLUME\/*\/BOOM Remake.app\/Contents\/Frameworks\/sfml-audio.framework\/Versions\/2.6.1\/sfml-audio",
    "name" : "sfml-audio",
    "CFBundleVersion" : "2.6.1"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 7152254976,
  "size" : 3136438272,
  "uuid" : "1df3dfc1-141a-35d0-a4e5-f1e113894c6e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=855.2M resident=0K(0%) swapped_out_or_unallocated=855.2M(100%)\nWritable regions: Total=1.6G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.6G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               512K        4 \nActivity Tracing                   256K        1 \nCG backing stores                 1920K        4 \nCG image                           160K        3 \nColorSync                          576K       25 \nCoreAnimation                     15.7M        5 \nCoreGraphics                        32K        2 \nCoreUI image data                 1072K        7 \nFoundation                          64K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           293.5M       55 \nMALLOC guard page                  192K        9 \nMALLOC_MEDIUM (reserved)         960.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        128K        1 \nSTACK GUARD                       56.2M       12 \nStack                             15.3M       12 \nVM_ALLOCATE                        640K       18 \nVM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)\n__AUTH                            1940K      190 \n__AUTH_CONST                      11.3M      353 \n__DATA                            9172K      353 \n__DATA_CONST                      12.9M      367 \n__DATA_DIRTY                       979K      123 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       585.7M       17 \n__OBJC_CONST                      1988K      161 \n__OBJC_RO                         82.9M        1 \n__OBJC_RW                         3152K        1 \n__TEXT                           269.5M      382 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      148.6M       21 \nshared memory                      928K       16 \n===========                     =======  ======= \nTOTAL                              2.8G     2160 \nTOTAL, minus reserved VM space     1.5G     2160 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6267122541fbd3022330c3ea"
      },
      "deploymentId" : 240000231
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 7459.101.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Feb  8 2022 01:44:45 version 18.60.21.0.7.8.126 FWID 01-1cdae627
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
```

**Comment by cdstanford** [comment]
I'm getting around 56 FPS in both fullscreen and windowed

**Comment by orazioedoardo** [comment]
> I did encounter a crash when changing the fullscreen resolution several times

Can you explain in more detail? First off, do you actually see the fullscreen option in preferences? As I explained above, in my testing SFML does not detect full screen resolutions on HiDPI displays. Second, when does it crash exactly? Does it crash every time (i.e. is it deterministic)? When you reopen, does it open on the resolution you have set?

> I'm getting around 56 FPS in both fullscreen and windowed

Good to know.

By the way, your macOS version if way out of date 1 year and 9 months ago. If you want to stay on Monterey, the latest version is 12.7.2

**Comment by orazioedoardo** [comment]
> I did encounter a crash when changing the fullscreen resolution several times

This is due to multiple state issues with the resolution confirmation prompt "Is this OK?" with YES/NO that appears when selecting a different resolution and pressing OK.

It's easy to miss and if you press OK twice, then go change the resolution again before the timer expires, lifish crashes (this is not limited to macOS).

The timer is also not reset between preferences loads, and pressing OK once and then Cancel doesn't revert to windowed or better the previous resolution.

Since I can't fix all of this now, I've just disabled it ([new build](https://github.com/orazioedoardo/lifish/actions/runs/7389675451/artifacts/1143790538)) to make a working release. 

> Only remaining Mac-specific issue as far as I can see is the fact that the app uses a lot of CPU by default even on the menu screen. The framerate is about 60 at the default 640p but decreases to 30 at 1080p. This doesn’t occur on Linux for example.

Me too can confirm  that the frame rate is very high even on HiDPI displays/Macs. All resolutions are available as well. This issue was limited to the virtual machine I was using for tests.

That said I think we are good to go @silverweed if you are ok with these changes.

**Comment by stacksjb** [comment]
Thx - I added a tracking issue for the resolution change bug so we can fix in the future. 

This has looked great from the testing!

**Comment by cdstanford** [comment]
One other thing I noticed on the most recently shared build is that the game asks for a high score name after each level (and adds an entry to the high score list), instead of just once per game. Possibly related to #16 , not sure

**Comment by orazioedoardo** [comment]
> the game asks for a high score name after each level

I noticed that too, it asks for player 2 specifically, even if you haven't actually played with it. It's not every time from what I've seen though, I think saving the games changes the circumstances in which it appears.

(note: it's not an issue introduced by this pull request)

**Comment by silverweed** [comment]
Sorry for the late reply, I just came back from vacation so I couldn't follow this thread properly.

> That said I think we are good to go @silverweed if you are ok with these changes.

The changes look good to me: I'll try to merge them and verify that it works fine on linux/windows asap.

@stacksjb do you still need documentation on the save format? It should be quite straightforward to understand from [here](https://github.com/silverweed/lifish/blob/boom/src/lifish/SaveManager.cpp#L72), but if you need more explanation let me know.

Update: I tested both on linux and windows and it seems to be working fine, so I'm merging this. Thanks to everyone for the contribution, particularly @orazioedoardo!
I'll prepare a new release soon on the official website as well.
